### ISSUE TITLE
Uncaught ReferenceError: git is not defined

### ISSUE THREAD

**Issue by lbs8901** [jacogr/atom-git-control#190]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [git-control](https://github.com/jacogr/atom-git-control) package, v0.7.1
### Stack Trace

Uncaught ReferenceError: git is not defined

```
At /Users/mp/.atom/packages/git-control/lib/git-control.coffee:50

ReferenceError: git is not defined
    at Object.module.exports.GitControl.updatePaths (/Users/mp/.atom/packages/git-control/lib/git-control.coffee:50:5)
    at /Users/mp/.atom/packages/git-control/lib/git-control.coffee:19:39
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.setPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:225:27)
    at Project.module.exports.Project.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:125:19)
    at Object.projectDeserialization (/Users/mp/.atom/packages/project-viewer/src/states.js:11:22)
    at pv-list-item.clickListener (/Users/mp/.atom/packages/project-viewer/src/list-item-component.js:75:17)
    at PVSelectListView.confirmed (/Users/mp/.atom/packages/project-viewer/src/select-view.js:65:49)
    at PVSelectListView.confirmSelection (/Users/mp/.atom/packages/project-viewer/src/select-view.js:56:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:19.2.0 command-palette:toggle (atom-pane.pane.active)
     -1:17.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:16.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -1:16.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:16.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:16.3.0 settings-view:view-installed-packages (atom-pane.pane.active)
  4x -1:16.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:12.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.9.0 git-control:toggle (div.package-detail.panels-item)
     -0:02.5.0 project-viewer:toggle-select-view (a.stack-toggle)
     -0:01.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:01.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "project-plus",
      "git-controlhub"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "git-control": {
    "showGitFlowButton": false
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.6.0
atom-ctags, v4.5.2
atom-webbrowser, v2.1.4
atomic-chrome, v0.3.0
browser-plus, v0.0.60
docs-snippets, v0.8.0
file-icons, v1.7.15
git-control, v0.7.1
git-log, v0.4.1
language-diff, v0.4.0
project-viewer, v0.3.12
quick-docs, v0.1.0
tabs-to-spaces, v1.0.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by requiemforameme** [comment]
I'm looking into this.
