### ISSUE TITLE
Uncaught Error: Command failed: ls `git rev-parse --git-dir` | grep rebase || echo norebase'ls' ...

### ISSUE THREAD

**Issue by Littlehhh** [jacogr/atom-git-control#237]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [git-control](https://github.com/jacogr/atom-git-control) package 0.9.0

### Stack Trace

Uncaught Error: Command failed: ls `git rev-parse --git-dir` | grep rebase || echo norebase
'ls' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

```
At child_process.js:538

Error: Command failed: ls `git rev-parse --git-dir` | grep rebase || echo norebase
'ls' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:495:13)
    at Object.execSync (child_process.js:535:13)
    at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:680:22)
    at runShell (/packages/git-control/lib/git-control-view.coffee:27:25)
    at GitControlView.module.exports.GitControlView.rebaseMenuClick (/packages/git-control/lib/git-control-view.coffee:245:13)
    at MenuView.module.exports.MenuView.click (/packages/git-control/lib/views/menu-view.coffee:50:7)
    at MenuItem.click (/packages/git-control/lib/views/menu-view.coffee:39:17)
    at /packages/git-control/node_modules/space-pen/lib/space-pen.js:231:38)
    at /packages/git-control/node_modules/jquery/dist/jquery.js:4435:9)
    at /packages/git-control/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -9:13.7.0 git-control:toggle (input.hidden-input)
     -5:16.7.0 core:save (input.hidden-input)
     -2:43 core:copy (atom-pane.pane.active)
     -1:45.3.0 git-control:toggle (div.package-detail.panels-item)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
git-control 0.9.0 
Hydrogen 1.12.1 
markdown-pdf 1.5.0 
markdown-preview-enhanced 0.12.1 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
simplified-chinese-menu 5.3.1 
```

**Comment by GeorgeWL** [comment]
The lead devs haven't made an update in 3 months and many of the features of this plugin are now built-in to Atom 1.18.0+

I'd recommend you act as if this git is dead, as the devs seem to have abandoned it and update to a version of Atom with the Git built-in.
