### ISSUE TITLE
Uncaught TypeError: repo.getOriginURL is not a function

### ISSUE THREAD

**Issue by foxdog05000** [jacogr/atom-git-control#238]
Hello !

1. Just open git-control with CTRL+ALT-O before commit

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: Windows 10
**Thrown From**: [git-control](https://github.com/jacogr/atom-git-control) package 0.9.0

### Stack Trace

Uncaught TypeError: repo.getOriginURL is not a function

```
At /C:/Users/far/.atom/packages/git-control/lib/git.coffee:219

TypeError: repo.getOriginURL is not a function
    at Object.hasOrigin (/packages/git-control/lib/git.coffee:144:17)
    at GitControlView.module.exports.GitControlView.fetchMenuClick (/packages/git-control/lib/git-control-view.coffee:200:25)
    at GitControlView.module.exports.GitControlView.update (/packages/git-control/lib/git-control-view.coffee:98:10)
    at Object.updateViews (/packages/git-control/lib/git-control.coffee:51:9)
    at /packages/git-control/lib/git-control.coffee:19:57
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.17.2/resources/app/src/workspace.js:489:1)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/workspace-center.js:16:1)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane-container.js:280:1)
    at Pane.module.exports.Pane.setActiveItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:318:1)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:471:1)
    at Object.toggleView (/packages/git-control/lib/git-control.coffee:37:12)
    at /packages/git-control/lib/git-control.coffee:18:57)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -6:15.1.0 core:save (input.hidden-input)
  4x -5:31 core:backspace (input.hidden-input)
     -5:28.2.0 intentions:highlight (input.hidden-input)
     -5:28.2.0 editor:move-to-end-of-word (input.hidden-input)
     -5:26.3.0 intentions:highlight (input.hidden-input)
     -5:26.2.0 core:save (input.hidden-input)
     -2:14.7.0 intentions:highlight (input.hidden-input)
     -2:13.5.0 git-control:toggle (input.hidden-input)
     -1:56.6.0 intentions:highlight (input.hidden-input)
     -1:56.2.0 es6-javascript:end-line-comma (input.hidden-input)
  2x -1:54 intentions:highlight (input.hidden-input)
  3x -1:53.5.0 es6-javascript:end-line-comma (input.hidden-input)
  2x -1:20.6.0 core:backspace (input.hidden-input)
     -1:13.1.0 core:confirm (input.hidden-input)
     -0:06.8.0 intentions:highlight (input.hidden-input)
     -0:06.5.0 git-control:toggle (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.29.26 
atom-css-clean 2.20.5 
atom-es6-standard-snippets 1.2.0 
atom-hg 2.0.14 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
autocomplete-love 0.4.0 
busy-signal 1.4.3 
color-picker 2.2.5 
es6-javascript 1.0.0 
es6-snippets 0.3.0 
file-icons 2.1.7 
fold-functions 0.5.0 
fonts 2.1.0 
genesis-ui 0.5.0 
git-control 0.9.0 
intentions 1.1.2 
language-babel 2.65.1 
language-SCSS 0.4.0 
linter 2.1.4 
linter-htmlhint 1.3.3 
linter-js-standard 3.9.1 
linter-jshint 3.1.2 
linter-json-lint 0.1.2 
linter-ui-default 1.6.0 
nodejs-snippets 2.0.2 
pigments 0.39.1 
qolor 0.4.1 
tortoise-hg 1.0.0 
```

**Comment by foxdog05000** [comment]
Problem solved. Git-control tries to open my mercurial depots! So it does not work;) With a GIT repository everything works!
