### ISSUE TITLE
Uncaught TypeError: this.setworkspacetitle is not a function

### ISSUE THREAD

**Issue by MasaruKitajima** [jacogr/atom-git-control#251]
[Enter steps to reproduce:]

1. Menu->Package->git-control->Toggle

I've installed git-flow by `brew install git-flow-avh` .
And then did ` for file in `find /usr/local/bin -type f -iname git[-f]* -exec basename {} \;`; do sudo ln -s /usr/local/bin/$file /usr/bin/$file; done` .

How can I solve this?

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [git-control](https://github.com/jacogr/atom-git-control) package 0.9.0

### Stack Trace

Uncaught TypeError: this.setworkspacetitle is not a function

```
At /Users/thirstytraveler/.atom/packages/git-control/lib/git-control-view.coffee:76

TypeError: this.setworkspacetitle is not a function
    at GitControlView.module.exports.GitControlView.initialize (/packages/git-control/lib/git-control-view.coffee:76:5)
    at /packages/merge-conflicts/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/git-control/lib/git-control-view.coffee:36:7)
    at Object.toggleView (/packages/git-control/lib/git-control.coffee:31:18)
    at /packages/git-control/lib/git-control.coffee:18:57)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -9:17.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  3x -9:09.2.0 git-control:toggle (div.panels-item)
     -0:34.1.0 core:confirm (input.hidden-input)
     -0:03.6.0 git-control:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-bootstrap3 1.2.12 
atom-clock 0.1.15 
atom-ide-ui 0.5.4 
atom-jade 0.3.0 
atom-math 0.0.9 
autocomplete-json 5.5.0 
autocomplete-math 0.1.1 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
autocomplete-sql 0.5.0 
autocomplete-xml 0.9.4 
busy-signal 1.4.3 
color-picker 2.2.5 
csscomb 0.3.1 
docblockr 0.12.3 
document-outline 1.6.17 
editorconfig 2.2.2 
file-icons 2.1.13 
flex-tool-bar 0.12.0 
git-control 0.9.0 
ide-css 0.2.0 
ide-json 0.1.0 
ide-php 0.6.9 
japanese-menu 1.13.0 
language-blade 0.36.0 
language-markdown 0.25.1 
laravel 0.7.1 
laravel-forms-bootstrap-snippets 1.2.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
project-view 0.6.2 
regex-railroad-diagram 0.19.4 
Remote-FTP 1.3.1 
symbols-tree-view 0.14.0 
tabs-to-spaces 1.0.3 
tool-bar 1.1.0 
```

**Comment by CodeBrotha** [comment]
I get the same error on Windows 10.

**Comment by Seb182** [comment]
I get the same error on Linux Ubuntu 17.10.
