### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by RemiZOffAlex** [jacogr/atom-git-control#253]
Uncaught TypeError: Cannot read property 'split' of undefined
/home/master/.atom/packages/git-control/lib/git-control-view.coffee:76
Hide Stack Trace
TypeError: Cannot read property 'split' of undefined
    at GitControlView.module.exports.GitControlView.initialize (/home/master/.atom/packages/git-control/lib/git-control-view.coffee:76:50)
    at GitControlView.View [as constructor] (/home/master/.atom/packages/git-control/node_modules/space-pen/lib/space-pen.js:184:25)
    at new GitControlView (/home/master/.atom/packages/git-control/lib/git-control-view.coffee:36:7)
    at Object.toggleView (/home/master/.atom/packages/git-control/lib/git-control.coffee:31:18)
    at HTMLElement.<anonymous> (/home/master/.atom/packages/git-control/lib/git-control.coffee:18:57)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1382:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
The error was thrown from the git-control package. This issue has already been reported.

**Comment by jpoles1** [comment]
Same issue here.

**Comment by Vivisky** [comment]
+1

**Comment by Razoxane** [comment]
+1

**Comment by RW83** [comment]
+ 1

**Comment by bilyboy785** [comment]
+1

**Comment by RemiZOffAlex** [comment]
Alternative https://atom.io/packages/git-controlhub

**Comment by crphilipp** [comment]
+1

**Comment by carltonmason** [comment]
+1

**Comment by wesferr** [comment]
+1

**Comment by chrisloveit** [comment]
+1

**Comment by atompi** [comment]
# +1

**Comment by atompi** [comment]
It's worked !    
https://github.com/jacogr/atom-git-control/pull/247

**Comment by muhammetfaik** [comment]
+1

**Comment by milindhg** [comment]
same issue for me.

**Comment by xnyssxy** [comment]
same issue for me. how to fix it ?

**Comment by koss89** [comment]
+1
Atom 1.22.1 x64
Ubuntu 17.10

**Comment by kiochan** [comment]
+1

**Comment by SavageCore** [comment]
Please stop the +1's

You can thumb up the issue itself... Anyway, it is already fixed [here](https://github.com/jacogr/atom-git-control/pull/247#issuecomment-338564321) as @mission802 said.

**Comment by RemiZOffAlex** [comment]
And what's the problem to correct the github repository to update the package through the Atom Updater ???

**Comment by SavageCore** [comment]
Well, the problem is @jacogr and @MarcelMue seem to be MIA judging by the open issues and PRs

**Comment by cpierce** [comment]
@jacogr / @MarcelMue would you be willing to let me help with this project so that we can get this issue resolved and let people continue to use your great addition to atom?

**Comment by ranforce** [comment]
+1

**Comment by WitekS** [comment]
+1

**Comment by fransyozef** [comment]
+1

**Comment by oddlots** [comment]
+1

**Comment by jeancantu** [comment]
+1

**Comment by Skaidon** [comment]
+1

**Comment by irvnriir** [comment]
+1

**Comment by rawveg** [comment]
+1

**Comment by General-Beck** [comment]
ubuntu 17.10 Atom 1.24.0 x64
+

**Comment by Smokrow** [comment]
+1

**Comment by antoniochacon** [comment]
same in windows 10

**Comment by estevaocma** [comment]
+1

**Comment by suxiongit** [comment]
+1

**Comment by kguidonimartins** [comment]
+1

**Comment by lebernardo** [comment]
+1

**Comment by scrapyomama** [comment]
<img src="https://avatars2.githubusercontent.com/u/40560589?s=88&amp;v=4" style="max-width:100%;">
