### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by duxiaokang** [jacogr/atom-git-control#254]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [git-control](https://github.com/jacogr/atom-git-control) package 0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Users/duxiaokang/.atom/packages/git-control/lib/git-control-view.coffee:76

TypeError: Cannot read property 'split' of undefined
    at GitControlView.module.exports.GitControlView.initialize (/packages/git-control/lib/git-control-view.coffee:76:50)
    at /packages/merge-conflicts/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/git-control/lib/git-control-view.coffee:37:3)
    at Object.toggleView (/packages/git-control/lib/git-control.coffee:31:18)
    at /packages/git-control/lib/git-control.coffee:18:57)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1382:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -3:43.5.0 core:backspace (input.hidden-input)
     -3:00.9.0 core:save (input.hidden-input)
     -2:32.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-lunar-particle-syntax.theme-lunar-particle-ui)
  3x -1:58.5.0 git-control:toggle (input.hidden-input)
     -1:08.8.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:59.3.0 core:paste (input.hidden-input)
  3x -0:57.4.0 core:backspace (input.hidden-input)
     -0:30.7.0 core:close (div.package-detail.panels-item)
     -0:25.9.0 git-control:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-beautify 0.30.7 
atom-solarized-dark-ui 0.28.1 
atom-ternjs 0.18.3 
atom-webstorm-syntax-theme 0.0.2 
atom-webstorm-ui-theme 0.0.1 
autocomplete-paths 2.12.1 
duotone-dark-syntax 2.1.0 
file-icons 2.1.14 
git-checkout 0.3.2 
git-control 0.9.0 
git-log 0.4.1 
git-projects 1.17.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
lunar-particle-syntax 0.3.8 
lunar-particle-ui 0.3.13 
merge-conflicts 1.4.5 
one-dark-vivid-syntax 1.8.0 
pigments 0.40.2 
pretty-json 1.6.4 
simplified-chinese-menu 5.3.5 
snow-dark-syntax 0.1.1 
solarized-dark-ui 0.3.2 
solarized-light-ui 0.1.0 
spring-dark-syntax 0.0.4 
Sublime-Style-Column-Selection 1.7.4 
tree-view-git-status 1.4.0 
```

**Comment by wellmotta** [comment]
#259
