### ISSUE TITLE
Failed to activate the git-control package

### ISSUE THREAD

**Issue by GradyD** [jacogr/atom-git-control#43]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [git-control](https://github.com/jacogr/atom-git-control) package, v0.1.8

### Stack Trace

Failed to activate the git-control package

```
At Cannot read property 'getWorkingDirectory' of undefined

TypeError: Cannot read property 'getWorkingDirectory' of undefined
  at Object.<anonymous> (C:\Users\grady\.atom\packages\git-control\lib\git.coffee:16:13)
  at Object.<anonymous> (C:\Users\grady\.atom\packages\git-control\lib\git.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\grady\.atom\packages\git-control\lib\git-control-view.coffee:3:7)
  at Object.<anonymous> (C:\Users\grady\.atom\packages\git-control\lib\git-control-view.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\grady\.atom\packages\git-control\lib\git-control.coffee:1:18)
  at Object.<anonymous> (C:\Users\grady\.atom\packages\git-control\lib\git-control.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:672:34)
  at Package.module.exports.Package.activateConfig (C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:257:12)
  at Package.module.exports.Package.activateNow (C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:236:14)
  at C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:742:29
  at Emitter.module.exports.Emitter.emit (C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:227:20)
  at C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\grady\AppData\Local\atom\app-0.187.0\resources\app\src\window-event-handler.js:182:20)

```

### Commands

```
     -0:05.7 git-control:toggle (atom-text-editor.editor)
     -0:01.4 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.1
editorconfig, v0.3.0
git-control, v0.1.8
highlight-selected, v0.9.1
minimap, v4.5.0
project-manager, v1.15.5
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by wesleycoder** [comment]
+1 to be fixed.

This is happening in Linux x64 too.

**Comment by surdu** [comment]
In order to reproduce this: when you have no files/dir opened, try to open the git-control.

**Comment by wesleycoder** [comment]
Same error when I do this...

**Comment by ZucchiniZe** [comment]
I am also getting this on OS X 10.10

**Comment by Stsosz** [comment]
Getting this on OS X 10.10

**Comment by big-wave-tim** [comment]
I get this but only when working on directories or files that are not part of a git repository

**Comment by 190n** [comment]
I get this on Ubuntu 14.10. The project I got it in was not a git repo.

**Comment by EwanValentine** [comment]
+1 I have multiple git repo's as part of one bigger project

**Comment by shark4649** [comment]
Getting this on OS X 10.10. After installing again problem was solved.

**Comment by GradyD** [comment]
I no longer am having this issue. Once I updated Atom it started working again.

**Comment by MarcelMue** [comment]
I worked on a partial solution here: 4cc3e032df146987e959ea323a7376360e74d152 that atleast tells you more clearly what is happening or why git-control is not working. I am still looking for a decent fix but this is my current hacky workaround.

**Comment by Ilias48rus** [comment]
+1
