### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getWorkingDirectory' of undefined

### ISSUE THREAD

**Issue by redfrog** [jacogr/atom-git-control#55]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Mac OS X 10.9.5
**Thrown From**: [git-control](https://github.com/jacogr/atom-git-control) package, v0.1.9

### Stack Trace

Uncaught TypeError: Cannot read property 'getWorkingDirectory' of undefined

```
At /Users/redfrog/.atom/packages/git-control/lib/git.coffee:16

TypeError: Cannot read property 'getWorkingDirectory' of undefined
  at Object.<anonymous> (/Users/redfrog/.atom/packages/git-control/lib/git.coffee:16:13)
  at Object.<anonymous> (/Users/redfrog/.atom/packages/git-control/lib/git.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/redfrog/.atom/packages/git-control/lib/git-control-view.coffee:3:7)
  at Object.<anonymous> (/Users/redfrog/.atom/packages/git-control/lib/git-control-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/redfrog/.atom/packages/git-control/lib/git-control.coffee:1:18)
  at Object.<anonymous> (/Users/redfrog/.atom/packages/git-control/lib/git-control.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:667:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:239:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:155:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:193:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:219:24
  at /Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:368:19)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:275:26
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
autocomplete-emojis, v2.2.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.10.0
autocomplete-snippets, v1.2.0
file-icons, v1.5.4
git-log, v0.3.0
highlight-selected, v0.9.1
japanese-wrap, v0.2.7
language-haml, v0.19.0
line-jumper, v0.13.0
minimap, v4.7.6
minimap-git-diff, v4.1.2
open-recent, v2.2.2
show-ideographic-space, v0.1.6

# Dev
No dev packages
```

**Comment by MarcelMue** [comment]
See Issue #43
