### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by silarsis** [jacogr/atom-git-control#83]
[Enter steps to reproduce below:]

1. Changed something, committed, pushed

**Atom Version**: 0.205.0
**System**: Microsoft Windows 10 Home Insider Preview
**Thrown From**: [git-control](https://github.com/jacogr/atom-git-control) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At C:\Users\Kevin\.atom\packages\git-control\lib\dialogs\push-dialog.coffee:37

TypeError: Cannot read property 'split' of null
    at PushDialog.module.exports.PushDialog.push (C:\Users\Kevin\.atom\packages\git-control\lib\dialogs\push-dialog.coffee:96:35)
    at HTMLButtonElement.<anonymous> (C:\Users\Kevin\AppData\Local\atom\app-0.205.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\Kevin\AppData\Local\atom\app-0.205.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\Kevin\AppData\Local\atom\app-0.205.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -0:07.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.7.0 git-control:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
git-control, v0.3.0
language-docker, v1.1.3
language-powershell, v2.0.1

# Dev
No dev packages
```

**Comment by TheSHEEEP** [comment]
Same here, the repository does not yet have a master branch on remote. Maybe that is the problem?

1. Changed something, committed, pushed.


**Atom Version**: 1.3.3
**System**: "openSUSE Leap
**Thrown From**: [git-control](https://github.com/jacogr/atom-git-control) package, v0.4.0


### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /home/thesheeep/.atom/packages/git-control/lib/dialogs/push-dialog.coffee:37

TypeError: Cannot read property 'split' of null
    at PushDialog.module.exports.PushDialog.push (/home/thesheeep/.atom/packages/git-control/lib/dialogs/push-dialog.coffee:37:29)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:08.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -3:03.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:00.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:59.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:59.7.0 git-control:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "lime"
    ]
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.7.3
git-control, v0.4.0
haxe, v0.8.10
haxe-newfile, v0.5.0
indentation-indicator, v0.6.0
language-doxygen, v0.2.1
language-haxe, v0.3.1
linter, v1.11.3
markdown-preview-plus, v2.2.2
markdown-writer, v2.2.0
zentabs, v0.8.6

# Dev
No dev packages
```
