### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Mulletfingers999** [jacogr/atom-git-control#87]
Steps to reproduce: Packages -> git-control -> toggle. Crashes instantly and I cannot open the tab.

**Atom Version**: 0.165.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [git-control](https://github.com/jacogr/atom-git-control) package, v0.3.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/liam/.atom/packages/git-control/lib/git.coffee:130

TypeError: undefined is not a function
  at Object.module.exports.hasOrigin (/home/liam/.atom/packages/git-control/lib/git.coffee:130:17)
  at GitControlView.module.exports.GitControlView.fetchMenuClick (/home/liam/.atom/packages/git-control/lib/git-control-view.coffee:163:25)
  at GitControlView.module.exports.GitControlView.update (/home/liam/.atom/packages/git-control/lib/git-control-view.coffee:70:10)
  at Object.module.exports.GitControl.updateViews (/home/liam/.atom/packages/git-control/lib/git-control.coffee:44:9)
  at /home/liam/.atom/packages/git-control/lib/git-control.coffee:17:57
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:314:21)
  at Object.module.exports.GitControl.toggleView (/home/liam/.atom/packages/git-control/lib/git-control.coffee:34:12)
  at atom-workspace.<anonymous> (/home/liam/.atom/packages/git-control/lib/git-control.coffee:16:57)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -2:29.3 core:backspace (input.hidden-input)
     -2:25.6 snippets:next-tab-stop (input.hidden-input)
     -2:25.6 snippets:expand (input.hidden-input)
     -2:25.6 editor:indent (input.hidden-input)
     -2:25.2 emmet:insert-formatted-line-break-only (input.hidden-input)
     -2:25.2 editor:newline (input.hidden-input)
     -2:22.0 core:backspace (input.hidden-input)
  2x -2:21.4 core:move-right (input.hidden-input)
  2x -2:13.4 core:save (input.hidden-input)
     -0:29.7 open-on-github:history (ul.list-inline.tab-bar.inset-panel)
     -0:13.5 merge-conflicts:detect (input.hidden-input)
  2x -0:00.0 git-control:toggle (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atomatigit, v1.2.3
color-tabs, v0.0.1
emmet, v2.3.10
git-control, v0.3.0
linter, v0.12.0
linter-scspell, v1.1.1
merge-conflicts, v1.2.10
red-wavy-underline, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by MarcelMue** [comment]
Could this be related to your atom version? 0.165.0 seems to be a quite old version.

**Comment by Mulletfingers999** [comment]
Huh, didn't know 1.0 had come out yet... I'll update and report back when I get home.

**Comment by Mulletfingers999** [comment]
Yup, fixed it. Thanks ;)
